### PR TITLE
feature/make-your-first-deploy

### PR DESCRIPTION
**Pull request by rniedziolka**
Acceptance Criteria:

- You run seeds on production.
- The app is online and accessible in any browser.
- There is information in the Github repo's README on how to access the production and sign in.

### CODE REVIEW

**Review by ciejj — APPROVED** [review]
Good job 👍

**Comment by rniedziolka** [comment]
Thank you @ciejj !!!

**Review by oskarlakner — APPROVED** [review]
🙌

**Comment by rniedziolka** [comment]
Thanks guys!

**Comment by rniedziolka** [comment]
Thanks guys!

**Pull request merged**
